name: docker build and push image

on:
  push:
  workflow_dispatch:

env:
  OWNER_NAME: 1devops2
  REPOSITORY_NAME: how-to-configure-nginx-as-a-reverse-proxy-on-ubuntu

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          # tags: ${{ env.OWNER_NAME }}/${{ env.REPOSITORY_NAME }}:latest
          tags: ${{ env.OWNER_NAME }}/${{ env.REPOSITORY_NAME }}:${{ github.run_number }}

      - name: Run the docker container
        run: docker run -it -d -p 8080:80 ${{ env.OWNER_NAME }}/${{ env.REPOSITORY_NAME }}:${{ github.run_number }}

      - name: Wait for the container to start
        run: |
          echo "Waiting for the container to start..."
          sleep 5 # Adjust the sleep duration if needed

      - name: Verify the application is accessible
        run: |
          echo "Checking if the application is accessible..."
          for i in {1..5}; do
            if curl -s --head http://localhost:8080 | grep "200 OK"; then
              echo "Application is accessible."
              exit 0
            fi
            echo "Application is not accessible yet. Retrying in 5 seconds..."
            sleep 3
          done
          echo "Application is not accessible after multiple attempts."
          exit 1