name: docker build and push image

on:
  push:

env:
  OWNER_NAME: 1devops2
  REPOSITORY_NAME: how-to-configure-nginx-as-a-reverse-proxy-on-ubuntu

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.OWNER_NAME }}/${{ env.REPOSITORY_NAME }}:latest
          # tags: ${{ env.OWNER_NAME }}/${{ env.REPOSITORY_NAME }}:${{ github.run_number }}
